package com.sanalberto.ad_orm;
// Generated 11 ene. 2021 21:27:48 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Album generated by hbm2java
 */
@Entity
@Table(name = "Album", catalog = "chinook")
public class Album implements java.io.Serializable {

	private Integer albumId;
	private Artist artist;
	private String title;
	private Set<Track> tracks = new HashSet<Track>(0);

	public Album() {
	}

	public Album(Artist artist, String title) {
		this.artist = artist;
		this.title = title;
	}

	public Album(Artist artist, String title, Set<Track> tracks) {
		this.artist = artist;
		this.title = title;
		this.tracks = tracks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AlbumId", unique = true, nullable = false)
	public Integer getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	/*
	 * Relación varios a uno. 
	 * @JoinColumn Indica quién es el "dueño" de la relación (en esta suele ser el lado 1)
	 * FetchType.LAZY es para ahorrar recursos, cargará los datos cuando se necesiten
	 * */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ArtistId", nullable = false) 
	public Artist getArtist() {
		return this.artist;
	}

	public void setArtist(Artist artist) {
		this.artist = artist;
	}

	@Column(name = "Title", nullable = false, length = 160)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "album")
	public Set<Track> getTracks() {
		return this.tracks;
	}

	public void setTracks(Set<Track> tracks) {
		this.tracks = tracks;
	}

}
